# Generated by Django 5.1.7 on 2025-09-15 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facial_recognition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facialenrollment",
            name="aws_external_image_id",
            field=models.CharField(
                blank=True,
                help_text="AWS Rekognition External Image ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="facialenrollment",
            name="aws_face_id",
            field=models.CharField(
                blank=True,
                help_text="AWS Rekognition Face ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="facialenrollment",
            name="aws_image_id",
            field=models.CharField(
                blank=True,
                help_text="AWS Rekognition Image ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="facialenrollment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("DLIB", "DLIB (Legacy)"),
                    ("AWS_REKOGNITION", "AWS Rekognition"),
                ],
                default="AWS_REKOGNITION",
                help_text="Facial recognition provider",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="facialenrollment",
            name="embedding",
            field=models.BinaryField(
                blank=True, help_text="128-D facial embedding", null=True
            ),
        ),
        migrations.AlterField(
            model_name="facialenrollment",
            name="face_confidence",
            field=models.FloatField(
                help_text="Confidence score of face detection",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
