# Generated by Django 5.1.7 on 2025-08-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Courses (student groups) assigned to this faculty",
                related_name="faculties",
                to="students.studentgroup",
            ),
        ),
    ]
