# Generated by Django 5.1.7 on 2025-09-06 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("check_in", "Check In"),
                            ("check_out", "Check Out"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("enroll", "Biometric Enrollment"),
                            ("schedule_create", "Schedule Created"),
                            ("attendance_mark", "Attendance Marked"),
                            ("user_create", "User Created"),
                            ("group_create", "Group Created"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "target_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("target_id", models.CharField(blank=True, max_length=100, null=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="common_user_user_id_a130e1_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="common_user_action__07b5b3_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="common_user_created_fdbac8_idx"
                    ),
                ],
            },
        ),
    ]
