# Generated by Django 5.1.7 on 2025-08-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_transform_to_date_based_schedule"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="schedule",
            new_name="schedules_date_7fe978_idx",
            old_name="schedules_date_7fb8f8_idx",
        ),
        migrations.RenameIndex(
            model_name="schedule",
            new_name="schedules_date_9d5c9b_idx",
            old_name="schedules_date_e3a1f7_idx",
        ),
        migrations.AddField(
            model_name="schedule",
            name="days_of_week",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of weekday numbers 0-6 for weekly pattern",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="location",
            field=models.CharField(
                blank=True, help_text="Display location for frontend", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="recurrence_end_date",
            field=models.DateField(
                blank=True, help_text="End date for recurrence", null=True
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="recurrence_pattern",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="weekly",
                help_text="Pattern for recurrence when recurring is true",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="recurring",
            field=models.BooleanField(
                default=False, help_text="Whether this schedule recurs"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="room",
            field=models.CharField(
                blank=True, help_text="Room or location (legacy)", max_length=50
            ),
        ),
    ]
