# Generated by Django 5.1.7 on 2025-08-14 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0001_initial"),
        (
            "schedules",
            "0003_rename_schedules_date_7fb8f8_idx_schedules_date_7fe978_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                help_text="Faculty member teaching this class",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="faculty.faculty",
            ),
        ),
    ]
